I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 158, in script
    $ renpy.pause(0.05)
  File "game/script.rpy", line 158, in script
    $ renpy.pause(0.05)
  File "game/script.rpy", line 158, in <module>
    $ renpy.pause(0.05)
  File "renpy/common/00action_other.rpy", line 586, in __call__
    rv = self.callable(*self.args, **self.kwargs)
  File "game/script.rpy", line 82, in center_view_on_player
    renpy.call_in_new_context("labyrinthe_screen", center_x=center_x, center_y=center_y)
  File "game/script.rpy", line 169, in script
    label labyrinthe_screen:
  File "game/script.rpy", line 169, in script
    label labyrinthe_screen:
Exception: Arguments supplied, but parameter list not present

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\renpy-8.3.0-sdk\renpy\bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "C:\renpy-8.3.0-sdk\renpy\main.py", line 652, in main
    run(restart)
  File "C:\renpy-8.3.0-sdk\renpy\main.py", line 148, in run
    renpy.execution.run_context(True)
  File "C:\renpy-8.3.0-sdk\renpy\execution.py", line 958, in run_context
    context.run()
  File "game/script.rpy", line 158, in script
    $ renpy.pause(0.05)
  File "lib/python3.9/future/utils/__init__.py", line 444, in raise_
  File "game/script.rpy", line 158, in script
    $ renpy.pause(0.05)
  File "C:\renpy-8.3.0-sdk\renpy\ast.py", line 821, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\renpy-8.3.0-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 158, in <module>
    $ renpy.pause(0.05)
  File "C:\renpy-8.3.0-sdk\renpy\exports\statementexports.py", line 194, in pause
    rv = renpy.ui.interact(mouse='pause', type='pause', roll_forward=roll_forward, pause=delay, pause_modal=modal)
  File "C:\renpy-8.3.0-sdk\renpy\ui.py", line 301, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\renpy-8.3.0-sdk\renpy\display\core.py", line 2188, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "C:\renpy-8.3.0-sdk\renpy\display\core.py", line 3232, in interact_core
    rv = root_widget.event(ev, x, y, 0)
  File "C:\renpy-8.3.0-sdk\renpy\display\layout.py", line 1294, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\renpy-8.3.0-sdk\renpy\display\layout.py", line 1294, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\renpy-8.3.0-sdk\renpy\display\layout.py", line 1294, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\renpy-8.3.0-sdk\renpy\display\screen.py", line 793, in event
    rv = self.child.event(ev, x, y, st)
  File "C:\renpy-8.3.0-sdk\renpy\display\layout.py", line 1294, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\renpy-8.3.0-sdk\renpy\display\behavior.py", line 1180, in event
    return handle_click(self.clicked)
  File "C:\renpy-8.3.0-sdk\renpy\display\behavior.py", line 1101, in handle_click
    rv = run(action)
  File "C:\renpy-8.3.0-sdk\renpy\display\behavior.py", line 401, in run
    return action(*args, **kwargs)
  File "renpy/common/00action_other.rpy", line 586, in __call__
    rv = self.callable(*self.args, **self.kwargs)
  File "game/script.rpy", line 82, in center_view_on_player
    renpy.call_in_new_context("labyrinthe_screen", center_x=center_x, center_y=center_y)
  File "C:\renpy-8.3.0-sdk\renpy\game.py", line 377, in call_in_new_context
    return renpy.execution.run_context(False)
  File "C:\renpy-8.3.0-sdk\renpy\execution.py", line 958, in run_context
    context.run()
  File "game/script.rpy", line 169, in script
    label labyrinthe_screen:
  File "lib/python3.9/future/utils/__init__.py", line 444, in raise_
  File "game/script.rpy", line 169, in script
    label labyrinthe_screen:
  File "C:\renpy-8.3.0-sdk\renpy\ast.py", line 764, in execute
    values = apply_arguments(self.parameters, renpy.store._args, renpy.store._kwargs)
  File "C:\renpy-8.3.0-sdk\renpy\parameter.py", line 451, in apply_arguments
    raise Exception("Arguments supplied, but parameter list not present")
Exception: Arguments supplied, but parameter list not present

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.0.24082114
The Maze 1.0
Tue Sep  3 21:14:19 2024
